loadData([
	{
		"origin": "seloger.com",
		"origin_id": "144466297",
		"title": "Maison 5 pièces",
		"desc": "Maison récente de 120m² avec 4 chambres à Ornex. Une cuisine équipée et ouverte sur le séjour de 30m². Une chambre au rez-de-chaussée et 3 chambres à l'étage, dont l'une, parentale (salle d'eau et dressing). 2 salles d'eau et 1 salle de bain Un jardin d'environ 80 m² et un grand garage. À proximité de la ligne F des TPG et à 500m de Ferney-Voltaire. Livré de suite.",
		"price": "2200 €cc* * Loyer mensuel charges comprises",
		"area": "120 m²",
		"location": "01210 Ferney Voltaire",
		"pic": "https://v.seloger.com/s/crop/100x100/visuels/2/4/0/d/240d779j3zzw4xivml27mcq9xw869j4s2lno7etcw.jpg"
	},
	{
		"origin": "seloger.com",
		"origin_id": "140249945",
		"title": "Villa 4 pièces",
		"desc": "A 5 min du centre ville, Dans lotissement, proche toutes commodités villa mitoyenne avec cuisine équipée, séjour traversant, 3 chambres dont une avec salle de bains privative, 2 WC, 2 SALLES DE BAIN, coin bureau, garage er jardin, chauffage gazvisite virtuelle disponible sur notre site ABI.",
		"price": "1826 €cc* * Loyer mensuel charges comprises",
		"area": "104 m²",
		"location": "01210 Ferney-Voltaire",
		"pic": "https://v.seloger.com/s/crop/100x100/visuels/0/8/8/x/088xn97zr2bjorb6dcahtxcfsg8ab1mtnb190ohls.jpg"
	},
	{
		"origin": "seloger.com",
		"origin_id": "144511333",
		"title": "Maison 5 pièces",
		"desc": "Belle maison mitoyenne, sans vis à vis, d'une surface habitable de 120 m² + garage et jardin avec grande terrasse.\nCuisine équipée ouverte sur le salon séjour, accès extérieur, 1 chambre au rez avec salle de douches et 3 chambres à l'étage avec une salle de bains commune.\nUn garage pour une grande voiture et un espace buanderie est à votre disposition.\nProximité des Bus et des écoles.\nAlliance Property Management.",
		"price": "2200 €+ch [object Object]",
		"area": "120 m²",
		"location": "01210 Ferney-Voltaire",
		"pic": "https://v.seloger.com/s/crop/100x100/visuels/1/r/i/e/1riez8tori4dkcfr36zam8efyd3p2yab6shg8klky.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "85856",
		"title": "From Feb 23rd,  furnished room in Geneva (Onex area), for a non smoker girl",
		"desc": "Available from March 1st in Geneva (Onex district): furnished single use room, CHF 690.-/month, charges included, for a non-smoker girl preferably over 25. The room has sheets, blankets, pillows, bed, matress, table, chair, lamps, mirors. <br />\r\n<br />\r\nThe rent includes charges such as electricity, heating and water fees, and as Wfi Internet connection. Equipped shared kitchen, dining room, bathroom (incl. washing machine) and WC.<br />\r\n<br />\r\nRental period is from 2 to 6 months. The flat is located in Onex (Canton of Geneva, Switzerland), a residential and very safe area, within walking distance from main Swiss supermarkets (Coop, Migros, Denner, Aldi, Lidl, chemist, Post office...). <br />\r\n<br />\r\nClose to tramway line 14 (running frequently, every 5 minutes in the morning) stop \"Bandol\", it will take 20 minutes from \"Bandol\" stop to \"Gare Cornavin\" main train station. Geneva public transportation trip planner can be checked here : http://tpg.ch/en/web/site-international<br />\r\n<br />\r\nThe flat is to be shared with me, a Geneva University graduated guy working full time in Geneva, used to flatsharing, a graduated French girl, doing a traineeship in Geneva.<br />\r\n<br />\r\nPlease \"PM\" if interested. Reply to detailed emails with your precise rental period, and some details about you? Thanks! French and Spanish also spoken",
		"rooms": "5",
		"price": "650 CHF",
		"location": "Onex, Geneva, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/85/85856_bl_photo_499e1.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87187",
		"title": "5 rooms, 93 square meters. Near CERN and Tram",
		"desc": "Located in the new Eco Area with solar panels, near Cern, 2 mins from the Tram. <br />\r\n1 American kitchen fully equipped (Dish washer, fridge, oven...)<br />\r\n3 bedrooms with 1 master bedroom (WC and bathtub)<br />\r\n1 very big living room with full window<br />\r\n1 long balcony (entire apartment)<br />\r\n1 big cellar<br />\r\nAll equipped with floor heating system<br />\r\nBike lockers<br />\r\nElevators<br />\r\n3d floor facing the Jura<br />\r\nParking lot just below the apartment (for extra 190 chf)<br />\r\nTotally new, we were the first to take the lease.<br />\r\nTelereseau UPC<br />\r\nAll fees included.",
		"rooms": "5",
		"price": "3111 CHF",
		"location": "Geneva, Meyrin",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87187_bl_photo_e1e4d.jpeg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "69468",
		"title": "Beautiful 3 bedrooms flat in Cessy, 20 min from Geneva",
		"desc": "Sale to foreigners is permitted !<br />\r\n<br />\r\nIn Cessy (France), 20 min from Geneva: beautiful almost new flat (2010) T4 on 2nd floor in a secured residence, 102 sqm + 73 sqm terrace , offering an entrance with cupboard, nice fully equipped kitchen open to the living room with terrace, 3 bedrooms, one with shower room and access to terrace, bathroom, separate WC, cellar, 2 garages, 2 parking places, nice view. Excellent flat, must be visited. Train station Cornavin in Geneva is accessable by direct bus line F. Price: EUR 650'000 - negotiable! Tel. +41791961088",
		"rooms": "4",
		"price": "650000 CHF",
		"location": "route de Pitegny 195C, 01170 Cessy, France",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/69/69468_bl_photo_0e921.png"
	},
	{
		"origin": "glocals.com",
		"origin_id": "75719",
		"title": "Beautiful modern 5.5 rooms duplex in Bogis-Bossey",
		"desc": "Beautiful big 5.5 rooms duplex of 142 m2, on the 1st floor, in a modern residence built in 2008 in Bogis-Bossey, about 20 km from Geneva and only 2 km from International School of Geneva campus in Founex. The flat is composed as follows: on the 1st floor - entrance hall with fitted wardrobe, guest WC, bedroom with private shower room, nice fully equipped kitchen open onto the large living room with fireplace as well as the dining room, enjoying access to the large balcony of 22 m2 offering a clear view on the countryside. The 2nd floor - 2 bedrooms with fitted wardrobes, bathroom with jacuzzi, guest bedroom, large private laundry room with storage. The floor heating is convertible and can become a cooling system in summer. The flat has central vacuum cleaner. Large cellar of 13.5 m2 and two underground parking places complete this property. The flat is rented at Fr. 3800 per month.",
		"rooms": "5",
		"price": "1190000 CHF",
		"location": "chemin des Pralies 39, 1279 Bogis-Bossey near Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/75/75719_bl_photo_153b3.png"
	},
	{
		"origin": "glocals.com",
		"origin_id": "85390",
		"title": "Nice renovated 4-rooms flat in Grand-Lancy/Geneva",
		"desc": "Beautiful and sunny 4-rooms flat, renovated in 2018, on the 2nd floor in 80 avenue Eugène Lance, 1212 Grand-Lancy. It is composed as follows: entrance hall, sunny living room, fully equipped kitchen (stove, oven, fridge, freezer, dishwasher, washing-drying machine) semi-open on living room, two spacious bedrooms, bathroom with bath, sink and toilet, cellar. The flat is rented till the end of September 2019 at Fr. 2'650 per month including a flat amount of charges of Fr. 300 for heating, water and other expenses. Price is negotiable. Public transport stop Bachet: lines 12, 18, 23, 43, D, or Pontets or Palettes: lines 12, 15, 22, 23, 42.",
		"rooms": "4",
		"price": "700000 CHF",
		"location": "80 avenue Eugène Lance, 1212 Grand-Lancy, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/85/85390_bl_photo_db0f2.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "86117",
		"title": "Nice 4-rooms flat in Grand-Lancy(Geneva)",
		"desc": "Beautiful sunny 4-rooms flat of 71m2 in PPE on the 2nd floor in 80 avenue Eugène Lance, 1212 Grand-Lancy. It is composed as follows: entrance hall, living room with loggia of 4m2, kitchen, two bedrooms, bathroom, cellar. Needs some renovation. Price is negotiable. Public transport stop Bachet: lines 12, 18, 23, 43, D, or Pontets or Palettes: lines 12, 15, 22, 23, 42. <br />\r\n<br />\r\nBel appartement ensoleillé de 4 pièces de 71m2 en PPE au 2ème étage au 80 avenue Eugène Lance, 1212 Grand-Lancy. Il est composé comme suit: hall d'entrée, salon avec loggia de 4m2, cuisine, deux chambres à coucher, salle de bain, cave. Travaux à prévoir. Arrêt Bachet de transport publique: lignes 12, 18, 23, 43 ou Pontets ou Palettes: lignes 12, 15, 22, 23, 42.",
		"rooms": "4",
		"price": "660000 CHF",
		"location": "80 avenue Eugène Lance, 1212 Grand-Lancy, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/86/86117_bl_photo_65a9d.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87715",
		"title": "Cologny Penthouse with full Lake view for rent !",
		"desc": "Gorgeous 2 bedroom Maisonnette with 2 large open air terrace overlooking lake Léman and Salève mountains. 2 bathrooms a large living room with large bright windows and balcony on both sides. This penthouse is fully furnished and equipped ready to move in.",
		"rooms": "4",
		"price": "7500 CHF",
		"location": "Cologny, Cologny",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals0"
	},
	{
		"origin": "glocals.com",
		"origin_id": "72256",
		"title": "High Standard 3 BR apartment Ferney Voltaire near the border",
		"desc": "3 bedrrom apartment to sell in an elegant building dated from 2015, set in a quiet and green environment, near the Swiss border. The flat consists in a living room with a fully equipped modern design American kitchen, 3 bedrooms, 1 bathroom, 1 shower room, 1 toilet for visitors, 2 balconies/terrace, 2 wardrobes, 1 inside parking space, 1 storage room. High standard building. 498.000 Euros.",
		"rooms": "4",
		"price": "498000 CHF",
		"location": "Chemin de la planche brûlée, Ferney Voltaire - France",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/72/72256_bl_photo_654b3.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87227",
		"title": "Bright 2 bedroom apt in Ferney Voltaire (available for short or long stays)",
		"desc": "I rent bright 2-bedroom apt in Ferney Voltaire, 79sqm, South facing, fully furnished.<br />\r\nLocated in a quiet residential area, the apartment consists of a living room, 2 bedrooms, all of them with view on a park without face to face, modern fitted kitchen, bathroom with bathtub, separate wc, South facing balcony with table and chairs, 2 built in closets, washing machine, cellar, parking protected by security barriers, concierge, digi-code. <br />\r\nAvailable immediately! Short stays are welcome!<br />\r\nRental: 1390 EUR per month, heating and service charges included. Electricity is additional, approx 25EUR per month.<br />\r\nDirect rent from the owner!!",
		"rooms": "4",
		"price": "1590 CHF",
		"location": "Ferney Voltaire, Ferney Voltaire",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87227_bl_photo_2a9c2.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87713",
		"title": "Large, bright room to rent",
		"desc": "Large and bright room to rent in a charming 2-bedroom 110 sq m apartment with living room (plus fireplace), kitchen, separate dining room, large bathroom, separate WC. There is WIFI connection, TV, washing machine/ dryer, dishwasher, bed sheets and towels if required.<br />\r\n<br />\r\nThe apartment is centrally located 5 minutes’ walk to the lake and 2 minutes’ walk to Cornavin station, with easy access to bus and tram stops.<br />\r\n<br />\r\nIdeally, I am looking for someone who needs a place to stay during the week only. Initially short-term but can be flexible.  <br />\r\n<br />\r\nRent: CHF 1,100<br />\r\nPrice includes all charges and cleaner.<br />\r\n<br />\r\nIf you are interested or would like more information, please send a message.",
		"rooms": "4",
		"price": "1100 CHF",
		"location": "Centrally located, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87713_bl_photo_723d3.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "82136",
		"title": "UNIQUE 2 bedrooms apartment with private rooftop access for short term rental.",
		"desc": "SHARED APARTMENT WOULD BE OK AS WELL<br />\r\n<br />\r\nUnique 2 bedrooms penthouse duplex with private access to the rooftop of the building in trendy Carouge.<br />\r\n<br />\r\nIt consists of 2 spacious bedrooms with bay windows with a full view of the Jura mountain range, a bathroom and separate toilet.<br />\r\n<br />\r\nThe living room has bay windows with a magnificent view of the Salève.<br />\r\n<br />\r\nUpstairs, the contemporary kitchen, equipped with quality appliances, also has bay windows.<br />\r\n<br />\r\nThe 1st floor has 2 balconies and the upper floor where the kitchen is situated has 2 large terraces.<br />\r\n<br />\r\nIn addition, an access from the kitchen is provided to enjoy an extension on the terrace of the building. 35m2 rooftop on the roof of the building which will allow for a unique 360 degree view.<br />\r\n<br />\r\nThe apartment is 135 sq/m and tastefully furnished in the style of a boutique hotel.<br />\r\n<br />\r\nIt is located 50m from the Carouge tram stop and 1 tram stop from the future CEVA station.<br />\r\n<br />\r\nParking included<br />\r\n<br />\r\nA must see.<br />\r\n<br />\r\n-----------------------------------<br />\r\n<br />\r\nSuperbe appartement duplex traversant de 4 pièces situé en attique à Carouge.<br />\r\n<br />\r\nIl se compose de 2 chambres spacieuses bénéficiant de baies vitrées avec une vue complète sur la chaîne des montagnes du Jura, une salle de bain et des toilettes séparées.<br />\r\n<br />\r\nLe salon bénéficie de baies vitrées profitant d'une vue magnifique sur le Salève.<br />\r\n<br />\r\nA l'étage, la cuisine contemporaine, équipée d'électroménager de qualité, dispose de baies vitrées également.<br />\r\n<br />\r\nLe 1er étage a 2 balcons et l'étage supérieur ou se situe la cuisine dispose de 2 grandes terrasses.<br />\r\n<br />\r\nEn outre, il y a un accès depuis la cuisine pour profiter d'une extension sur la terrasse de l'immeuble permettant d'apprécier une vue à 360 degrés.<br />\r\n<br />\r\nL'appartement est traversant, fait 135m2 et est meublé avec goût à la manière d'un \"boutique hotel\".<br />\r\n<br />\r\nIl est situé à 50m de l'arrêt de tram Carouge et à 1 arrêt de tram de la future gare du CEVA.<br />\r\n<br />\r\nL'appartement possède un accès privé au toit de l'immeuble bénéficiant d'une vue à 360 degrés.<br />\r\n<br />\r\nParking compris<br />\r\n<br />\r\nA voir absolument.",
		"rooms": "4",
		"price": "4250 CHF",
		"location": "Carouge, carouge",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/82/82136_bl_photo_a8ee3.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87698",
		"title": "4 piece apart in Grand Saconnex, near Health Campus, UN, WIPO, WHO; EcolInt",
		"desc": "We are leaving our bright, spacious split-level apartment in the northwest part of city. (Grand Saconnex 1218, Chemin Jaques Attenville 11 , situated in a private, child-friendly complex.<br />\r\n<br />\r\nThis is a contract direct with the lovely owners, not via the Regie. Rent is 2950 including water and heat, 2 parking spaces, 2 caves.<br />\r\n<br />\r\nThe apartment is a 4 piece apartment, approx 80 mp.<br />\r\n<br />\r\nIt has 2 large bedrooms, one living room and kitchen, one bathroom with a bathtub and 1 toilet:<br />\r\n<br />\r\n1 mezzanine bedroom – it comes with a separate dressing room with a closet for clothes, an ironing board and an iron, one new bed (160*200) bought from IKEA in September 2018 and a great mattress.<br />\r\n<br />\r\n1 child bedroom or spare/office on the first floor – comes with a bed (140*200), a spacious build-in closet, a big Ikea shelf for books/toys;<br />\r\n<br />\r\n1 bright, airy living room with tall windows, owners beautiful paintings on the walls, 1 sofa, 1 IKEA shelf to accommodate the TV, the TV, 2 armchairs, 1 small table for drinks for the sofa area, 1 wood shelf for books and papers, a dozen IKEA storage boxes.<br />\r\n<br />\r\n1 fully fitted kitchen – comes with plates, tableware, glasses, all sorts of pots and pans, vacuum cleaner, cleaning bucket, broom - all you need is to move.<br />\r\n<br />\r\n1 dining area with either a wool table or a glass table (both are available to chose) <br />\r\n<br />\r\n1 bathroom with a bathtub, 1 toilet and deposit under the sink for towels.<br />\r\n<br />\r\nA big superb terrace with views of the Jura and a private garden/play area. <br />\r\n<br />\r\nThere are 2 parking spaces included (one in front of the house, one underground in the garage), 2 big caves and a washer and drier in the basement only for this apartment. <br />\r\n<br />\r\nThe UN, WHO, ILO, IRC, WIPO and Global Fund are a short walk away, as is the airport (just 20 mins). CERN is within easy reach by tram. <br />\r\n<br />\r\nIt's a fantastic area to live, leafy streets, friendly neighbors, quiet surrounds, all amenities, private garden, kid friendly, easy walk/bus to the lake (bus 3 stop Giacometti or bus 22/3 Maison de Parliament 2 min) or center with some nice restaurants and parks nearby also. <br />\r\n<br />\r\nThe apartment is available from 16 of April. <br />\r\n<br />\r\nFor visits please reach out via glocals or mobile +41 79 422 64 12 (Cristina)<br />\r\n<br />\r\nAvailable: Apr 16, 2019<br />\r\n<br />\r\n| Location: Grand Saconnex, Geneva",
		"rooms": "4",
		"price": "2950 CHF",
		"location": "Jacques Attenville 11, Geneva - Grand Saconnex",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87698_bl_photo_7eedf.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87510",
		"title": "Appartement for sale",
		"desc": "Genève Centre-ville<br />\r\n<br />\r\n4 Pièces<br />\r\n94m2 + 5m2 balcon + 7m2 terrasse<br />\r\n<br />\r\nSitué dans le centre de Genève, à 500m de Bel-air, vue sur le lac et à deux pas du quartier des banques, cet appartement offre une surface de 94m2, un balcon de 5m2 et une terrasse de 7m2 au 1e étage d'un immeuble moderne. Disposant de 2 chambres, 2 salles de bain (dont 1 avec WC, 1 avec baignoire et WC), une cuisine équipée, un grand salon, une place de parking en sous-sol et une cave, il est idéalement placé à proximité des transport publiques et des commerces. Buanderie et local vélo dans la copropriété.",
		"rooms": "4",
		"price": "1150000 CHF",
		"location": "Geneva center, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87510_bl_photo_b99a8.png"
	},
	{
		"origin": "glocals.com",
		"origin_id": "85737",
		"title": "Private bedroom near CERN",
		"desc": "Great place to live and work near CERN, Geneva Airport is 20 mi by car. Crozet cable car 10 min.<br />\r\nThere is a direct bus 66 to the airport and Palexpo, bus 68-Cern. The bus stop is 5 min from the apartment.<br />\r\nParking is free of charge.<br />\r\nThe is a central heating, the hot water is central.<br />\r\nThe price is final- 850 chf and includes everything!<br />\r\nA friendly family atmosphere.<br />\r\nWhatsApp is available.",
		"rooms": "5",
		"price": "850 CHF",
		"location": ", Saint Genis Pouilly",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/85/85737_bl_photo_4ec01.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "85431",
		"title": "Room --\r\nEaux-Vives",
		"desc": "Yesterday I received a quite unexected cancellation of a booking for 1 March which means that I can now offer a room for immediate or nearly so occupation.<br />\r\n<br />\r\nThe room is in my own well-furnished apartment where the ambiance, in keeping with the building's other residents, is more a mix of occasional chit-chatting and observing one’s own space rather thanin weekend partying.<br />\r\n<br />\r\n<br />\r\nThe bathroom (separate WC) and independent, eat-in-size kitchen are shared and the rental period can be anything between one calendar month and a much longer stay, depending …<br />\r\n<br />\r\nIf interested, please send me a few details about your study and/or work plans, your rental budget, etc., so that I can respond in kind and set up an rdv for you to view.<br />\r\n<br />\r\nThanks for reading, and hope to hear from you,<br />\r\nRitchie",
		"rooms": "5",
		"price": "0 CHF",
		"location": "Eaux-Vives, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals0"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87578",
		"title": "4 PIECES APARTMENT MEYRIN",
		"desc": "Very luminous apartment. 4 pieces: 2rooms, 1living room + kitchen. 9th floor.<br />\r\n<br />\r\nPrice: 1910+120CHF<br />\r\n<br />\r\nPhotos: https://drive.google.com/open?id=1l-HjehmBa0iWAhj7A9qFedBAkLqMVDMe<br />\r\n<br />\r\nVisits and more info contact (whatsapp): +34662129413 +34650262766",
		"rooms": "4",
		"price": "1910 CHF",
		"location": "Meyrin, 1217",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87578_bl_photo_abd6e.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87707",
		"title": "5,5 rooms in Plainpalais, Geneva",
		"desc": "Beautiful corner apartment with lots of light, open view to Plainpalais square. <br />\r\n5,5 rooms (approx 110m2): <br />\r\n- 2 spacious bedrooms (one with walk-in closet)<br />\r\n- Large living room/dining room with balcony<br />\r\n- Separate kitchen, toilet, bathroom and storage room.<br />\r\nThe apartment has good storage space and built-in cupboards.  Kitchen is equipped, including also dishwasher and laundry machine. Also cave and bike storage.<br />\r\nCHF 3,300 / month including charges. <br />\r\nAvailable in early or mid-April 2019 (by agreement). <br />\r\nDossier required. <br />\r\nPlease PM for visits or questions.",
		"rooms": "5",
		"price": "3300 CHF",
		"location": "1205 Plainpalais, Geneve",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87707_bl_photo_54642.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "85828",
		"title": "2 bedrooms (T3) fully renovated comfy furnished apart in Ferney-Voltaire!",
		"desc": "2 bedrooms (T3) fully renovated furnished apart in Ferney-Voltaire. <br />\r\n<br />\r\n<br />\r\n75m2 + large balcony (12m2, that's where you can smoke, if you do), located in a nice private condo with a huge yard and a security gate. <br />\r\n<br />\r\n2 private parking spaces included + a storage room in the basement. <br />\r\n<br />\r\nThe apart has just been FULLY RENOVATED : 1) Totally new modern kitchen, 2) New wooden floor, 3) Renovated bathroom and 4) New custom made closet in the master bedroom.<br />\r\n<br />\r\nApart is fully furnished with flat screen TV, high speed internet (optic fiber), washing machine, dishwasher and fully equipped new kitchen (with new high quality induction cooking plates and oven, microwave etc). <br />\r\n<br />\r\n1 Queen size bed in the master bedroom. <br />\r\n1 bed in the second bedroom, that turns into a queen size double bed if needed. <br />\r\n<br />\r\nThe place is very quiet, very green and well located, on Route du Chateau: 1km away from Ferney’s city center (shops, Carrefour supermarket, famer’s market and restaurants). 20 minutes away from place des Nations, in Geneva.<br />\r\n<br />\r\nPease note that I will only accept application from people that will have a car at their disposal.  <br />\r\n<br />\r\nPrice is 1850euro/months (+ charges: electricity, water, local taxes) : +/- 200euro/months, depending on your consumption.<br />\r\n<br />\r\nInternet (high speed optic fiber) will be included in the monthly rent until July 2019.<br />\r\n<br />\r\nAvailable as of mid March 2019.<br />\r\n<br />\r\nSuitable for short and long term rental. <br />\r\n<br />\r\nBefore considering organizing a visit, please provide me with the following info in your application (bcharlier@gmail.com):<br />\r\n <br />\r\n1.Family situation (number of people who will be living in the apartment), <br />\r\n<br />\r\n2.Professional situation, <br />\r\n<br />\r\n3.Desired length of rental,<br />\r\n<br />\r\n4.Confirmation that you will have a car at your disposal.<br />\r\n<br />\r\nEmail (bcharlier@gmail.com) or Whatsapp (+41799281091) me for further info, including additional pictures/video of the apartment.<br />\r\n<br />\r\nBenji",
		"rooms": "4",
		"price": "2100 CHF",
		"location": ", Ferney Voltaire, FR",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/85/85828_bl_photo_f2cf9.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87705",
		"title": "Womand (friend of mine) renting 2 separate rooms near UNO",
		"desc": "Beautiful and lovely furnished apartment, crossing and spacious, facing the lake with a tremendous view on the Mont-Blanc, located on the last floor of a charming private building, only accessible by safety code.<br />\r\n<br />\r\nLocated in Bellevue-Genthod, 150 meters away from the trains station, 1.5 k away from international organization, 5 minutes drive away from the airport. Convenience stores and services nearby.<br />\r\n<br />\r\nTwo independent bedrooms well separated, quiet and completely furnished with storage cabinets, work desk and comfortable bedding (sheets and towels available), both opening on the quiet side of the building.<br />\r\n<br />\r\nKitchen fully equipped with oven, microwave, fridge-freezer, cooker, dishwasher.<br />\r\n<br />\r\nLarge and sunny living room, comfortable sofa, plasma TV, cable network, Wi-Fi.<br />\r\n<br />\r\nSeparate bathroom and restroom with washing machine and clothes dryer.<br />\r\n<br />\r\nMonthly rent per person: CHF 1’000",
		"rooms": "6",
		"price": "1000 CHF",
		"location": ", Genthod-Bellevue",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87705_bl_photo_94e6f.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87550",
		"title": "Charming 5 bedrooms semi-detached furnished house for rent - EUR 1930.-",
		"desc": "To rent in Nangy: large furnished 5 bedrooms house (125 m2) with big terrace and garden. Nangy is a pretty little village located 15 minutes from Geneva, 3 minutes drive from the highway and new hospital (CHAL). The house is located in a quiet dead end path with beautiful views over the fields and mountains. Schools are across the road. Fully equipped with many large dressings. Available early April. Please call or email for more information.",
		"rooms": "7",
		"price": "0 CHF",
		"location": "15 min from Geneva border, NANGY - FRANCE",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87550_bl_photo_f2a94.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "85856",
		"title": "From Feb 23rd,  furnished room in Geneva (Onex area), for a non smoker girl",
		"desc": "Available from March 1st in Geneva (Onex district): furnished single use room, CHF 690.-/month, charges included, for a non-smoker girl preferably over 25. The room has sheets, blankets, pillows, bed, matress, table, chair, lamps, mirors. <br />\r\n<br />\r\nThe rent includes charges such as electricity, heating and water fees, and as Wfi Internet connection. Equipped shared kitchen, dining room, bathroom (incl. washing machine) and WC.<br />\r\n<br />\r\nRental period is from 2 to 6 months. The flat is located in Onex (Canton of Geneva, Switzerland), a residential and very safe area, within walking distance from main Swiss supermarkets (Coop, Migros, Denner, Aldi, Lidl, chemist, Post office...). <br />\r\n<br />\r\nClose to tramway line 14 (running frequently, every 5 minutes in the morning) stop \"Bandol\", it will take 20 minutes from \"Bandol\" stop to \"Gare Cornavin\" main train station. Geneva public transportation trip planner can be checked here : http://tpg.ch/en/web/site-international<br />\r\n<br />\r\nThe flat is to be shared with me, a Geneva University graduated guy working full time in Geneva, used to flatsharing, a graduated French girl, doing a traineeship in Geneva.<br />\r\n<br />\r\nPlease \"PM\" if interested. Reply to detailed emails with your precise rental period, and some details about you? Thanks! French and Spanish also spoken",
		"rooms": "5",
		"price": "650 CHF",
		"location": "Onex, Geneva, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/85/85856_bl_photo_499e1.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87187",
		"title": "5 rooms, 93 square meters. Near CERN and Tram",
		"desc": "Located in the new Eco Area with solar panels, near Cern, 2 mins from the Tram. <br />\r\n1 American kitchen fully equipped (Dish washer, fridge, oven...)<br />\r\n3 bedrooms with 1 master bedroom (WC and bathtub)<br />\r\n1 very big living room with full window<br />\r\n1 long balcony (entire apartment)<br />\r\n1 big cellar<br />\r\nAll equipped with floor heating system<br />\r\nBike lockers<br />\r\nElevators<br />\r\n3d floor facing the Jura<br />\r\nParking lot just below the apartment (for extra 190 chf)<br />\r\nTotally new, we were the first to take the lease.<br />\r\nTelereseau UPC<br />\r\nAll fees included.",
		"rooms": "5",
		"price": "3111 CHF",
		"location": "Geneva, Meyrin",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87187_bl_photo_e1e4d.jpeg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "69468",
		"title": "Beautiful 3 bedrooms flat in Cessy, 20 min from Geneva",
		"desc": "Sale to foreigners is permitted !<br />\r\n<br />\r\nIn Cessy (France), 20 min from Geneva: beautiful almost new flat (2010) T4 on 2nd floor in a secured residence, 102 sqm + 73 sqm terrace , offering an entrance with cupboard, nice fully equipped kitchen open to the living room with terrace, 3 bedrooms, one with shower room and access to terrace, bathroom, separate WC, cellar, 2 garages, 2 parking places, nice view. Excellent flat, must be visited. Train station Cornavin in Geneva is accessable by direct bus line F. Price: EUR 650'000 - negotiable! Tel. +41791961088",
		"rooms": "4",
		"price": "650000 CHF",
		"location": "route de Pitegny 195C, 01170 Cessy, France",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/69/69468_bl_photo_0e921.png"
	},
	{
		"origin": "glocals.com",
		"origin_id": "75719",
		"title": "Beautiful modern 5.5 rooms duplex in Bogis-Bossey",
		"desc": "Beautiful big 5.5 rooms duplex of 142 m2, on the 1st floor, in a modern residence built in 2008 in Bogis-Bossey, about 20 km from Geneva and only 2 km from International School of Geneva campus in Founex. The flat is composed as follows: on the 1st floor - entrance hall with fitted wardrobe, guest WC, bedroom with private shower room, nice fully equipped kitchen open onto the large living room with fireplace as well as the dining room, enjoying access to the large balcony of 22 m2 offering a clear view on the countryside. The 2nd floor - 2 bedrooms with fitted wardrobes, bathroom with jacuzzi, guest bedroom, large private laundry room with storage. The floor heating is convertible and can become a cooling system in summer. The flat has central vacuum cleaner. Large cellar of 13.5 m2 and two underground parking places complete this property. The flat is rented at Fr. 3800 per month.",
		"rooms": "5",
		"price": "1190000 CHF",
		"location": "chemin des Pralies 39, 1279 Bogis-Bossey near Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/75/75719_bl_photo_153b3.png"
	},
	{
		"origin": "glocals.com",
		"origin_id": "85390",
		"title": "Nice renovated 4-rooms flat in Grand-Lancy/Geneva",
		"desc": "Beautiful and sunny 4-rooms flat, renovated in 2018, on the 2nd floor in 80 avenue Eugène Lance, 1212 Grand-Lancy. It is composed as follows: entrance hall, sunny living room, fully equipped kitchen (stove, oven, fridge, freezer, dishwasher, washing-drying machine) semi-open on living room, two spacious bedrooms, bathroom with bath, sink and toilet, cellar. The flat is rented till the end of September 2019 at Fr. 2'650 per month including a flat amount of charges of Fr. 300 for heating, water and other expenses. Price is negotiable. Public transport stop Bachet: lines 12, 18, 23, 43, D, or Pontets or Palettes: lines 12, 15, 22, 23, 42.",
		"rooms": "4",
		"price": "700000 CHF",
		"location": "80 avenue Eugène Lance, 1212 Grand-Lancy, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/85/85390_bl_photo_db0f2.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "86117",
		"title": "Nice 4-rooms flat in Grand-Lancy(Geneva)",
		"desc": "Beautiful sunny 4-rooms flat of 71m2 in PPE on the 2nd floor in 80 avenue Eugène Lance, 1212 Grand-Lancy. It is composed as follows: entrance hall, living room with loggia of 4m2, kitchen, two bedrooms, bathroom, cellar. Needs some renovation. Price is negotiable. Public transport stop Bachet: lines 12, 18, 23, 43, D, or Pontets or Palettes: lines 12, 15, 22, 23, 42. <br />\r\n<br />\r\nBel appartement ensoleillé de 4 pièces de 71m2 en PPE au 2ème étage au 80 avenue Eugène Lance, 1212 Grand-Lancy. Il est composé comme suit: hall d'entrée, salon avec loggia de 4m2, cuisine, deux chambres à coucher, salle de bain, cave. Travaux à prévoir. Arrêt Bachet de transport publique: lignes 12, 18, 23, 43 ou Pontets ou Palettes: lignes 12, 15, 22, 23, 42.",
		"rooms": "4",
		"price": "660000 CHF",
		"location": "80 avenue Eugène Lance, 1212 Grand-Lancy, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/86/86117_bl_photo_65a9d.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87715",
		"title": "Cologny Penthouse with full Lake view for rent !",
		"desc": "Gorgeous 2 bedroom Maisonnette with 2 large open air terrace overlooking lake Léman and Salève mountains. 2 bathrooms a large living room with large bright windows and balcony on both sides. This penthouse is fully furnished and equipped ready to move in.",
		"rooms": "4",
		"price": "7500 CHF",
		"location": "Cologny, Cologny",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals0"
	},
	{
		"origin": "glocals.com",
		"origin_id": "72256",
		"title": "High Standard 3 BR apartment Ferney Voltaire near the border",
		"desc": "3 bedrrom apartment to sell in an elegant building dated from 2015, set in a quiet and green environment, near the Swiss border. The flat consists in a living room with a fully equipped modern design American kitchen, 3 bedrooms, 1 bathroom, 1 shower room, 1 toilet for visitors, 2 balconies/terrace, 2 wardrobes, 1 inside parking space, 1 storage room. High standard building. 498.000 Euros.",
		"rooms": "4",
		"price": "498000 CHF",
		"location": "Chemin de la planche brûlée, Ferney Voltaire - France",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/72/72256_bl_photo_654b3.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87227",
		"title": "Bright 2 bedroom apt in Ferney Voltaire (available for short or long stays)",
		"desc": "I rent bright 2-bedroom apt in Ferney Voltaire, 79sqm, South facing, fully furnished.<br />\r\nLocated in a quiet residential area, the apartment consists of a living room, 2 bedrooms, all of them with view on a park without face to face, modern fitted kitchen, bathroom with bathtub, separate wc, South facing balcony with table and chairs, 2 built in closets, washing machine, cellar, parking protected by security barriers, concierge, digi-code. <br />\r\nAvailable immediately! Short stays are welcome!<br />\r\nRental: 1390 EUR per month, heating and service charges included. Electricity is additional, approx 25EUR per month.<br />\r\nDirect rent from the owner!!",
		"rooms": "4",
		"price": "1590 CHF",
		"location": "Ferney Voltaire, Ferney Voltaire",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87227_bl_photo_2a9c2.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87713",
		"title": "Large, bright room to rent",
		"desc": "Large and bright room to rent in a charming 2-bedroom 110 sq m apartment with living room (plus fireplace), kitchen, separate dining room, large bathroom, separate WC. There is WIFI connection, TV, washing machine/ dryer, dishwasher, bed sheets and towels if required.<br />\r\n<br />\r\nThe apartment is centrally located 5 minutes’ walk to the lake and 2 minutes’ walk to Cornavin station, with easy access to bus and tram stops.<br />\r\n<br />\r\nIdeally, I am looking for someone who needs a place to stay during the week only. Initially short-term but can be flexible.  <br />\r\n<br />\r\nRent: CHF 1,100<br />\r\nPrice includes all charges and cleaner.<br />\r\n<br />\r\nIf you are interested or would like more information, please send a message.",
		"rooms": "4",
		"price": "1100 CHF",
		"location": "Centrally located, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87713_bl_photo_723d3.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "82136",
		"title": "UNIQUE 2 bedrooms apartment with private rooftop access for short term rental.",
		"desc": "SHARED APARTMENT WOULD BE OK AS WELL<br />\r\n<br />\r\nUnique 2 bedrooms penthouse duplex with private access to the rooftop of the building in trendy Carouge.<br />\r\n<br />\r\nIt consists of 2 spacious bedrooms with bay windows with a full view of the Jura mountain range, a bathroom and separate toilet.<br />\r\n<br />\r\nThe living room has bay windows with a magnificent view of the Salève.<br />\r\n<br />\r\nUpstairs, the contemporary kitchen, equipped with quality appliances, also has bay windows.<br />\r\n<br />\r\nThe 1st floor has 2 balconies and the upper floor where the kitchen is situated has 2 large terraces.<br />\r\n<br />\r\nIn addition, an access from the kitchen is provided to enjoy an extension on the terrace of the building. 35m2 rooftop on the roof of the building which will allow for a unique 360 degree view.<br />\r\n<br />\r\nThe apartment is 135 sq/m and tastefully furnished in the style of a boutique hotel.<br />\r\n<br />\r\nIt is located 50m from the Carouge tram stop and 1 tram stop from the future CEVA station.<br />\r\n<br />\r\nParking included<br />\r\n<br />\r\nA must see.<br />\r\n<br />\r\n-----------------------------------<br />\r\n<br />\r\nSuperbe appartement duplex traversant de 4 pièces situé en attique à Carouge.<br />\r\n<br />\r\nIl se compose de 2 chambres spacieuses bénéficiant de baies vitrées avec une vue complète sur la chaîne des montagnes du Jura, une salle de bain et des toilettes séparées.<br />\r\n<br />\r\nLe salon bénéficie de baies vitrées profitant d'une vue magnifique sur le Salève.<br />\r\n<br />\r\nA l'étage, la cuisine contemporaine, équipée d'électroménager de qualité, dispose de baies vitrées également.<br />\r\n<br />\r\nLe 1er étage a 2 balcons et l'étage supérieur ou se situe la cuisine dispose de 2 grandes terrasses.<br />\r\n<br />\r\nEn outre, il y a un accès depuis la cuisine pour profiter d'une extension sur la terrasse de l'immeuble permettant d'apprécier une vue à 360 degrés.<br />\r\n<br />\r\nL'appartement est traversant, fait 135m2 et est meublé avec goût à la manière d'un \"boutique hotel\".<br />\r\n<br />\r\nIl est situé à 50m de l'arrêt de tram Carouge et à 1 arrêt de tram de la future gare du CEVA.<br />\r\n<br />\r\nL'appartement possède un accès privé au toit de l'immeuble bénéficiant d'une vue à 360 degrés.<br />\r\n<br />\r\nParking compris<br />\r\n<br />\r\nA voir absolument.",
		"rooms": "4",
		"price": "4250 CHF",
		"location": "Carouge, carouge",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/82/82136_bl_photo_a8ee3.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87698",
		"title": "4 piece apart in Grand Saconnex, near Health Campus, UN, WIPO, WHO; EcolInt",
		"desc": "We are leaving our bright, spacious split-level apartment in the northwest part of city. (Grand Saconnex 1218, Chemin Jaques Attenville 11 , situated in a private, child-friendly complex.<br />\r\n<br />\r\nThis is a contract direct with the lovely owners, not via the Regie. Rent is 2950 including water and heat, 2 parking spaces, 2 caves.<br />\r\n<br />\r\nThe apartment is a 4 piece apartment, approx 80 mp.<br />\r\n<br />\r\nIt has 2 large bedrooms, one living room and kitchen, one bathroom with a bathtub and 1 toilet:<br />\r\n<br />\r\n1 mezzanine bedroom – it comes with a separate dressing room with a closet for clothes, an ironing board and an iron, one new bed (160*200) bought from IKEA in September 2018 and a great mattress.<br />\r\n<br />\r\n1 child bedroom or spare/office on the first floor – comes with a bed (140*200), a spacious build-in closet, a big Ikea shelf for books/toys;<br />\r\n<br />\r\n1 bright, airy living room with tall windows, owners beautiful paintings on the walls, 1 sofa, 1 IKEA shelf to accommodate the TV, the TV, 2 armchairs, 1 small table for drinks for the sofa area, 1 wood shelf for books and papers, a dozen IKEA storage boxes.<br />\r\n<br />\r\n1 fully fitted kitchen – comes with plates, tableware, glasses, all sorts of pots and pans, vacuum cleaner, cleaning bucket, broom - all you need is to move.<br />\r\n<br />\r\n1 dining area with either a wool table or a glass table (both are available to chose) <br />\r\n<br />\r\n1 bathroom with a bathtub, 1 toilet and deposit under the sink for towels.<br />\r\n<br />\r\nA big superb terrace with views of the Jura and a private garden/play area. <br />\r\n<br />\r\nThere are 2 parking spaces included (one in front of the house, one underground in the garage), 2 big caves and a washer and drier in the basement only for this apartment. <br />\r\n<br />\r\nThe UN, WHO, ILO, IRC, WIPO and Global Fund are a short walk away, as is the airport (just 20 mins). CERN is within easy reach by tram. <br />\r\n<br />\r\nIt's a fantastic area to live, leafy streets, friendly neighbors, quiet surrounds, all amenities, private garden, kid friendly, easy walk/bus to the lake (bus 3 stop Giacometti or bus 22/3 Maison de Parliament 2 min) or center with some nice restaurants and parks nearby also. <br />\r\n<br />\r\nThe apartment is available from 16 of April. <br />\r\n<br />\r\nFor visits please reach out via glocals or mobile +41 79 422 64 12 (Cristina)<br />\r\n<br />\r\nAvailable: Apr 16, 2019<br />\r\n<br />\r\n| Location: Grand Saconnex, Geneva",
		"rooms": "4",
		"price": "2950 CHF",
		"location": "Jacques Attenville 11, Geneva - Grand Saconnex",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87698_bl_photo_7eedf.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87510",
		"title": "Appartement for sale",
		"desc": "Genève Centre-ville<br />\r\n<br />\r\n4 Pièces<br />\r\n94m2 + 5m2 balcon + 7m2 terrasse<br />\r\n<br />\r\nSitué dans le centre de Genève, à 500m de Bel-air, vue sur le lac et à deux pas du quartier des banques, cet appartement offre une surface de 94m2, un balcon de 5m2 et une terrasse de 7m2 au 1e étage d'un immeuble moderne. Disposant de 2 chambres, 2 salles de bain (dont 1 avec WC, 1 avec baignoire et WC), une cuisine équipée, un grand salon, une place de parking en sous-sol et une cave, il est idéalement placé à proximité des transport publiques et des commerces. Buanderie et local vélo dans la copropriété.",
		"rooms": "4",
		"price": "1150000 CHF",
		"location": "Geneva center, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87510_bl_photo_b99a8.png"
	},
	{
		"origin": "glocals.com",
		"origin_id": "85737",
		"title": "Private bedroom near CERN",
		"desc": "Great place to live and work near CERN, Geneva Airport is 20 mi by car. Crozet cable car 10 min.<br />\r\nThere is a direct bus 66 to the airport and Palexpo, bus 68-Cern. The bus stop is 5 min from the apartment.<br />\r\nParking is free of charge.<br />\r\nThe is a central heating, the hot water is central.<br />\r\nThe price is final- 850 chf and includes everything!<br />\r\nA friendly family atmosphere.<br />\r\nWhatsApp is available.",
		"rooms": "5",
		"price": "850 CHF",
		"location": ", Saint Genis Pouilly",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/85/85737_bl_photo_4ec01.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "85431",
		"title": "Room --\r\nEaux-Vives",
		"desc": "Yesterday I received a quite unexected cancellation of a booking for 1 March which means that I can now offer a room for immediate or nearly so occupation.<br />\r\n<br />\r\nThe room is in my own well-furnished apartment where the ambiance, in keeping with the building's other residents, is more a mix of occasional chit-chatting and observing one’s own space rather thanin weekend partying.<br />\r\n<br />\r\n<br />\r\nThe bathroom (separate WC) and independent, eat-in-size kitchen are shared and the rental period can be anything between one calendar month and a much longer stay, depending …<br />\r\n<br />\r\nIf interested, please send me a few details about your study and/or work plans, your rental budget, etc., so that I can respond in kind and set up an rdv for you to view.<br />\r\n<br />\r\nThanks for reading, and hope to hear from you,<br />\r\nRitchie",
		"rooms": "5",
		"price": "0 CHF",
		"location": "Eaux-Vives, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals0"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87578",
		"title": "4 PIECES APARTMENT MEYRIN",
		"desc": "Very luminous apartment. 4 pieces: 2rooms, 1living room + kitchen. 9th floor.<br />\r\n<br />\r\nPrice: 1910+120CHF<br />\r\n<br />\r\nPhotos: https://drive.google.com/open?id=1l-HjehmBa0iWAhj7A9qFedBAkLqMVDMe<br />\r\n<br />\r\nVisits and more info contact (whatsapp): +34662129413 +34650262766",
		"rooms": "4",
		"price": "1910 CHF",
		"location": "Meyrin, 1217",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87578_bl_photo_abd6e.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87707",
		"title": "5,5 rooms in Plainpalais, Geneva",
		"desc": "Beautiful corner apartment with lots of light, open view to Plainpalais square. <br />\r\n5,5 rooms (approx 110m2): <br />\r\n- 2 spacious bedrooms (one with walk-in closet)<br />\r\n- Large living room/dining room with balcony<br />\r\n- Separate kitchen, toilet, bathroom and storage room.<br />\r\nThe apartment has good storage space and built-in cupboards.  Kitchen is equipped, including also dishwasher and laundry machine. Also cave and bike storage.<br />\r\nCHF 3,300 / month including charges. <br />\r\nAvailable in early or mid-April 2019 (by agreement). <br />\r\nDossier required. <br />\r\nPlease PM for visits or questions.",
		"rooms": "5",
		"price": "3300 CHF",
		"location": "1205 Plainpalais, Geneve",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87707_bl_photo_54642.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "85828",
		"title": "2 bedrooms (T3) fully renovated comfy furnished apart in Ferney-Voltaire!",
		"desc": "2 bedrooms (T3) fully renovated furnished apart in Ferney-Voltaire. <br />\r\n<br />\r\n<br />\r\n75m2 + large balcony (12m2, that's where you can smoke, if you do), located in a nice private condo with a huge yard and a security gate. <br />\r\n<br />\r\n2 private parking spaces included + a storage room in the basement. <br />\r\n<br />\r\nThe apart has just been FULLY RENOVATED : 1) Totally new modern kitchen, 2) New wooden floor, 3) Renovated bathroom and 4) New custom made closet in the master bedroom.<br />\r\n<br />\r\nApart is fully furnished with flat screen TV, high speed internet (optic fiber), washing machine, dishwasher and fully equipped new kitchen (with new high quality induction cooking plates and oven, microwave etc). <br />\r\n<br />\r\n1 Queen size bed in the master bedroom. <br />\r\n1 bed in the second bedroom, that turns into a queen size double bed if needed. <br />\r\n<br />\r\nThe place is very quiet, very green and well located, on Route du Chateau: 1km away from Ferney’s city center (shops, Carrefour supermarket, famer’s market and restaurants). 20 minutes away from place des Nations, in Geneva.<br />\r\n<br />\r\nPease note that I will only accept application from people that will have a car at their disposal.  <br />\r\n<br />\r\nPrice is 1850euro/months (+ charges: electricity, water, local taxes) : +/- 200euro/months, depending on your consumption.<br />\r\n<br />\r\nInternet (high speed optic fiber) will be included in the monthly rent until July 2019.<br />\r\n<br />\r\nAvailable as of mid March 2019.<br />\r\n<br />\r\nSuitable for short and long term rental. <br />\r\n<br />\r\nBefore considering organizing a visit, please provide me with the following info in your application (bcharlier@gmail.com):<br />\r\n <br />\r\n1.Family situation (number of people who will be living in the apartment), <br />\r\n<br />\r\n2.Professional situation, <br />\r\n<br />\r\n3.Desired length of rental,<br />\r\n<br />\r\n4.Confirmation that you will have a car at your disposal.<br />\r\n<br />\r\nEmail (bcharlier@gmail.com) or Whatsapp (+41799281091) me for further info, including additional pictures/video of the apartment.<br />\r\n<br />\r\nBenji",
		"rooms": "4",
		"price": "2100 CHF",
		"location": ", Ferney Voltaire, FR",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/85/85828_bl_photo_f2cf9.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87705",
		"title": "Womand (friend of mine) renting 2 separate rooms near UNO",
		"desc": "Beautiful and lovely furnished apartment, crossing and spacious, facing the lake with a tremendous view on the Mont-Blanc, located on the last floor of a charming private building, only accessible by safety code.<br />\r\n<br />\r\nLocated in Bellevue-Genthod, 150 meters away from the trains station, 1.5 k away from international organization, 5 minutes drive away from the airport. Convenience stores and services nearby.<br />\r\n<br />\r\nTwo independent bedrooms well separated, quiet and completely furnished with storage cabinets, work desk and comfortable bedding (sheets and towels available), both opening on the quiet side of the building.<br />\r\n<br />\r\nKitchen fully equipped with oven, microwave, fridge-freezer, cooker, dishwasher.<br />\r\n<br />\r\nLarge and sunny living room, comfortable sofa, plasma TV, cable network, Wi-Fi.<br />\r\n<br />\r\nSeparate bathroom and restroom with washing machine and clothes dryer.<br />\r\n<br />\r\nMonthly rent per person: CHF 1’000",
		"rooms": "6",
		"price": "1000 CHF",
		"location": ", Genthod-Bellevue",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87705_bl_photo_94e6f.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87550",
		"title": "Charming 5 bedrooms semi-detached furnished house for rent - EUR 1930.-",
		"desc": "To rent in Nangy: large furnished 5 bedrooms house (125 m2) with big terrace and garden. Nangy is a pretty little village located 15 minutes from Geneva, 3 minutes drive from the highway and new hospital (CHAL). The house is located in a quiet dead end path with beautiful views over the fields and mountains. Schools are across the road. Fully equipped with many large dressings. Available early April. Please call or email for more information.",
		"rooms": "7",
		"price": "0 CHF",
		"location": "15 min from Geneva border, NANGY - FRANCE",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87550_bl_photo_f2a94.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "86954",
		"title": "Fully Furnished Luminous Flat (70m2)-2 Bedrooms-Balcony & Parking:EUR 1500/month",
		"desc": "AVAILABLE 1st FEBRUARY 2019 (Flexible)<br />\r\nContact me to arrange a viewing.<br />\r\n<br />\r\nRENT EUR 1'500.- / month charges included (central heating / cold & hot water)<br />\r\n<br />\r\n- 3RD FLOOR of a secured residence with interphone.<br />\r\n- BALCONY with stunning VIEW ON THE MONT-BLANC! <br />\r\n- PARKING available in the residence.<br />\r\n- 70M2<br />\r\n- LIFT<br />\r\n<br />\r\n- Very well situated flat close to COLLEX-BOSSY border (1km) and GENEVA (10km) - opposite International Lycée de Ferney-Voltaire.<br />\r\n\t\t\t\t\t<br />\r\n- Opposite TPG bus stop 'Ferney - Avenue de Vessy / Ferney Lycée' (Line 66) and connected to 'F' bus - 'Avenue du Jura' to United Nations Organizations; CERN; GVA Airport & Geneva railway station Cornavin.<br />\r\n\t\t\t\t\t<br />\r\n- 15 mins walking distance to Carrefour Supermarket, Cinema Voltaire (original version films), local french bakery, Post office, pharmacy, restaurants and Ferney-Voltaire market (every saturdays).<br />\r\n\t\t\t\t\t<br />\r\n- Close to Ferney Sports Centre: Fitness Centre; Swimming pool & Tennis club (indoor & outdoor courts) Football club.<br />\r\n<br />\r\nLIVING & DINING ROOM:\t\t\t\t\t<br />\r\n- Dining wooden table & chairs.<br />\r\n- Glass coffee table<br />\r\n- Comfortable large King size sofa bed.<br />\r\n- Flat screen TV <br />\r\n- TV furniture <br />\r\n- Bar cabinet<br />\r\n\t\t\t\t\t<br />\r\nKITCHEN:\t\t\t\t\t<br />\r\nSpacious & luminous fully furnished with many storage cabinets <br />\r\n- Gas Cooker<br />\r\n- Oven <br />\r\n- Microwave\t\t\t\t\t<br />\r\n- Fridge & Freezer 3 storage <br />\r\n- Dishwasher <br />\r\n- Washing machine <br />\r\n- Pots; pans; cutlery; plates; glasses; toaster<br />\r\n\t\t\t\t\t<br />\r\nBALCONY :\t\t\t\t\t<br />\r\n- Stunning view on the Mont-Blanc. <br />\r\n- Wood deck tiles covered.<br />\r\n- Foldable balcony table.<br />\r\n- Kitchen & living room connected<br />\r\n\t\t\t\t\t\t\t\t\t<br />\r\nBEDROOM No.1\t\t\t\t\t<br />\r\n- King size bed & mattress with storage bed base. <br />\r\n- Large mirrored wardrobe.<br />\r\n- View on the Jura mountains.<br />\r\n\t\t\t\t\t<br />\r\nBEDROOM No.2\t\t\t\t\t<br />\r\n- King size sofa bed.<br />\r\n- Wardrobe & furniture.<br />\r\n- View on the Jura mountains.<br />\r\n\t\t\t\t\t<br />\r\nDRESSING\t\t\t\t\t<br />\r\n- Separate and very spacious.<br />\r\n\t\t\t\t\t<br />\r\nBATHROOM<br />\r\n- Brand new & fully equipped. <br />\r\n- Spacious shower cabin.<br />\r\n- Towel radiator.",
		"rooms": "5",
		"price": "0 CHF",
		"location": "Ferney-Voltaire, Ferney-Voltaire",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/86/86954_bl_photo_b058c.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87697",
		"title": "4 Bedroom w/ Yard & Garage in Ornex, France 2200 EURO/month",
		"desc": "120 m²  recently built house available on at 1491 rue de Genève, F-01210 Ornex. Rent 2200 euros a month.<br />\r\n<br />\r\nFully equipped kitchen (diswahser, microwave, refrigerator, stove, oven), 4 bedrooms, 1 bathroom, 2 shower rooms, 2 toilets, garage, washing maching, lawnmower, terrace, garden, land 250 m². <br />\r\nMaster bedroom with en suite shower room and dressing room. Cost effective town gas central heating. Excellent insulation.<br />\r\n<br />\r\nVery close to Ferney Voltaire, Geneva and Public transport. F bus is right outside.<br />\r\n<br />\r\nThe house is located in the back row of the estate, which is the quietest.<br />\r\n<br />\r\nPlease contact Jean-Michel Veuillen at veuillen@gmail.com or +334 76 90 10 72.",
		"rooms": "6",
		"price": "2200 CHF",
		"location": "Ornex, France, Ornex",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87697_bl_photo_f9cd2.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87685",
		"title": "Superbly located, loft-style, two-bedroom apartment",
		"desc": "Located on the 5th floor of a beautiful old building in Augustins, between the Rue de Carouge and the HUG, this is a great value two-bedroom property rental opportunity.<br />\r\n<br />\r\nOn the 12 and 18 (Cornavin & Cern) tram routes, a 7-min walk to the Old Town, Plainpalais and under 10 mins to Carouge, there are seven supermarkets within 500 metres, lots of shops, restaurants, cafes etc. in this buzzing part of Geneva.<br />\r\n<br />\r\nThe flat itself is spacious with a big open-plan living room and kitchen annex, bathroom, two bedrooms and a cave in the basement. Option to buy existing washing machine and dishwasher and other fittings (e.g. shelves, desk unit). Parquet flooring throughout.<br />\r\n<br />\r\nThe unfurnished apartment is available as a long-term (1 year+) rent takeover.",
		"rooms": "4",
		"price": "2600 CHF",
		"location": "Augustins, Genève",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87685_bl_photo_bdb87.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87692",
		"title": "Split-level house for rent in Prévessin, 106 m2 available immediately, rent 2100",
		"desc": "Luminous split-level house available for rent in Prévessin, 5 min from Ferney by car, bus stop 66 and 64 at 100 m from the house.<br />\r\nComprises 3 bedrooms (2 with closets and one with balcony), large and fully equipped kitchen, living room, bathroom, separate visitor’s toilet, hall with closet, large wooden terrace, 100 m2 garden, garage and 25 m2 basement.<br />\r\nBedrooms with hardwood floors. New radiators, washing machine and dishwasher installed. Tiled living room and kitchen. Neutral decor throughout.<br />\r\nFor visits and information please contact us at nadmas@bluewin.ch",
		"rooms": "5",
		"price": "2100 CHF",
		"location": "Prévessin, Prévessin",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87692_bl_photo_fbe4f.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "76412",
		"title": "City living with historic accents - perfect for the modern family ***** (46)",
		"desc": "(046) Furnished 3BR duplex in Nyon Center *****<br />\r\nThis tastefully renovated apartment is a perfect blend of modern design and respect to it's history. It is situated in the center of Nyon close to restaurants, transportation and shopping. Beautiful wood beams, stonework and light fill the apartment that showcases beautiful, comfortable furnishing in every room. It boasts 3 double bedrooms it can host up to 6 people. New kitchen with all modern equipment. Fully outfitted with WIFI, cable television and exercise equipment, this apartment is perfect to work from home or just relax!<br />\r\n <br />\r\nFacilities :  Air Conditioning, Animals on demand, Babycot , Babyseat , Bed 180 , Bed 90, Dishwasher, Dryer in flat, Full kitchenware , Hairdryer, Heating , Non smoking, Oven, Refrigerator & Freezer , TV, Transportation facilities, Vacuum cleaner, ironing board and iron , Walking distance to the lake , Washing machine in flat, Weekly cleaning and Exit cleaning on demand (not included) , WiFi<br />\r\n<br />\r\neShortRental<br />\r\nTemporary Furnished Accommodations<br />\r\nTél. +41 76 411 08 58<br />\r\nEasy, Online Booking http://www.eshortrental.com<br />\r\nhttps://www.facebook.com/eshortrental<br />\r\n<br />\r\nAbout eShortRental :<br />\r\neShortRental provides furnished short-term accommodations and rentals in the Geneva, Vaud and Zurich regions for people from all over the world. If you are on business, an expatriate searching for a new accommodation, on holiday or renovating your home, you can find your \"new home away from home\" with us.",
		"rooms": "5",
		"price": "5500 CHF",
		"location": "Nyon, Nyon",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/76/76412_bl_photo_0329a.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87688",
		"title": "4 rooms apartment, 70m2, in the heart of Eaux-Vives and next to the lake",
		"desc": "FLAT DETAILS<br />\r\n4 rooms apartment structured as follows:<br />\r\n- Kitchen with dining space with multiple cupboards<br />\r\n- Big parental bedroom with 2 built-in cupboards<br />\r\n- Bathroom with bath-tube <br />\r\n- Living room opening on the dining room. Possibility of splitting the 2 rooms with plasterboard to create a child bedroom.<br />\r\n- Separate toilet<br />\r\n- Riddance<br />\r\nWooden floor, balcony opening on every room.<br />\r\nApartment on the 4th floor, with every great sun light all-day-long.<br />\r\nIndividual cellar. Share laundry room and bike parking.<br />\r\n<br />\r\nAVAILABILITY<br />\r\nEntry date: April 15th <br />\r\n<br />\r\nRENT<br />\r\nRent: 2'016 CHF / Charges: 250 CHF / Total: 2'266 CHF<br />\r\n<br />\r\nGROUPED VISITS<br />\r\nCome directly at Avenue de la Grenade 19, 1207 GENEVA and ring at LAVILLE at one of the below time: <br />\r\n- Thursday, February 28th from 8.30am till 10am<br />\r\n- Friday, March 1st from 5pm till 6.30Pm<br />\r\n- Saturday, March 2nd from 8.45am till 10am<br />\r\nThanks for coming with a full dossier (ID, work permit - if applicable, salary attestation, last 3 months pay-slip, non-poursuite attestation, civil responsibility attestation).",
		"rooms": "4",
		"price": "2266 CHF",
		"location": "Eaux-Vives, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87688_bl_photo_18ebe.jpeg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87686",
		"title": "Magnifique T4 en duplex avec jardin à Divonne",
		"desc": "FR : Appartement 4 pièces (T4) en duplex d’une superficie de 73m2 et son jardin à Divonne les Bains, France, dans une villa récente. Trois chambres, séjour donnant sur le jardin, cuisine entièrement équipée. Cave, garage intérieur et place de parking privé. <br />\r\n<br />\r\n<br />\r\nEN : Three-bedroom duplex apartment of 73 sqm & garden for sale in Divonne-les-Bains built recently. Fully equipped kitchen, spacious living room, garden. Cellar, indoor garage and private outside parking.",
		"rooms": "4",
		"price": "490000 CHF",
		"location": "Divonne-les-Bains, France, Divonne-les-Bains",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87686_bl_photo_87433.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87663",
		"title": "Elegant Bourgeois Villa for Sale in Tougin, Gex, France",
		"desc": "Elegant Bourgeoise House for sale in Gex<br />\r\n<br />\r\nLarge family house of 253 m2 living space comprised of 5 bedrooms, 3 full bathrooms (2 \"ensuite\"), 2 visitors toilettes, laundry room, double garage, 3 space carport and garden shed.  The house/property sits in a rare park of woodland of 3,366m2 <br />\r\nsurrounded by a terrace of 200m2.  High quality construction; Zeyko kitchen, central vacuum system, water softener, gas heating, alarm and main front gates enclosing 8 houses on 22,000m2.  <br />\r\nWalking distance from town, shopping and private school Jeanne D'Arc.<br />\r\nMaison Blanche Golf Club within 10 minutes drive and 15 mins to airport.<br />\r\nEuros 935,000.-<br />\r\nContact person;<br />\r\nChrista <br />\r\n<br />\r\nMob.  0041 (0) 79 200 85 32<br />\r\nchristabijoux@bluewin.ch",
		"rooms": "8",
		"price": "1050000 CHF",
		"location": "267, rue de Pré-Bailly, Tougin, Gex, France",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87663_bl_photo_aa55c.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87131",
		"title": "200 qm, spacious 5 bedrooms is available for rental or sale, Ferney, center.",
		"desc": "Exclusivity in Ferney-Voltaire (the French town bordering Geneva), in a residence located in the former park of the Voltaire Castle, completely fenced and provided with a beautiful common garden, retaining the charm of the walls and a huge wrought iron gate.<br />\r\n<br />\r\noffered the luxurious furnished T5 in triplex, <br />\r\nwith individual entrance. <br />\r\n<br />\r\nАround 200 m2 of the total area + 2 balconies: <br />\r\nentrance with a closet, <br />\r\n<br />\r\non the first level, a large living room with a powerful and modern design fireplace of 14 kW that can self-heat the whole apartment, a chic massive oak floor, built-in audio system, Italian kitchen of the Varenna brand, fully equipped with high-quality electrical appliances Gaggenau, steam oven, cellar wine cooler, granite island, guest WC, shower room, laundry. <br />\r\n<br />\r\nOn the second floor there are 3 bedrooms with spacious wardrobes: a large master bedroom with exposed beams and a ceiling height of more than 3.60m, with an attached big wardrobe; 2 large bedrooms with fitted wardrobes and high ceilings, bathroom. Individual gas heating remotely controlled via a smartphone. Water softener. <br />\r\nHigh-quality services. <br />\r\n<br />\r\nIdeal for families with children; a well-known private French school is located directly opposite the residence. There is a bus stop at the foot of the residence, direction to Geneva, international organisations, and the airport. 2 minutes’ drive to the border with Geneva. No pets allowed.<br />\r\n<br />\r\nCheck the address on googlemap to see how closed to United Nations and other International Organization and to GENEVA Airport. Postale Code 01210 Ferney-Voltaire - France. <br />\r\n<br />\r\nFerney-Voltaire is a small town where a lot of expats lives because it is very convenient place, especially for those who are working to one of the International Organization in Geneva, Geneva Airport, CERN, and WTC. Please Check the public transportation time table on WWW.TPG.CH. Buses are 64, Y & O.<br />\r\n<br />\r\nPrice € 4300 / month + charges € 200 / month <br />\r\nfor long term rental. <br />\r\n<br />\r\nAlso available for SALE.<br />\r\n<br />\r\nDirect with owner. <br />\r\n<br />\r\nContact: immoferney@gmail.com - Ask for our brochure",
		"rooms": "7",
		"price": "4500 CHF",
		"location": "rue de Gex, Ferney-Voltaire",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87131_bl_photo_deac9.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87562",
		"title": "Apartment New in the heart of Pâquis, 3 bedrooms, terrace of 47 m²,total 155 m².",
		"desc": "Apartment New in the heart of Pâquis, 3 bedrooms,135m2 plus terrace of 47 m².  <br />\r\n<br />\r\nDo not miss !<br />\r\n<br />\r\nLocated in the heart of the Pâquis, close to the Cornavin train station and Lake Geneva, the banking district, this superb new apartment of 3 bedrooms offers an exceptional location with a big terrace.<br />\r\n<br />\r\nDistribution:<br />\r\n- Large entrance with cupboards<br />\r\n- WC visitors<br />\r\n- Fully equipped open kitchen with central island <br />\r\n- Large living / dining room angle opening onto the terrace with sliding doors<br />\r\n- Office space with wardrobes <br />\r\n- Big bathroom with space for washing machine column and dryer <br />\r\n<br />\r\nNight part:<br />\r\n- 2 bedrooms with wardrobes, both with terrace access<br />\r\n- Master bedroom with large wardrobes and shower room - WC<br />\r\n<br />\r\nElectric blinds (with central locking), adjustable heating system by room controlled by a central lcd screen, lighting and water on the terrace, concierge in the building, mailbox system with order for receiving parcels.<br />\r\nLocal bike for two bikes, laundry room.<br />\r\n<br />\r\nRent: CHF 5900. -<br />\r\nCharges: CHF 250. -<br />\r\nParking: CHF 250. - (underground location)<br />\r\nAddress: Pellegrino-Rossi 16, 1201 Genève<br />\r\nAvailability at convenience<br />\r\nDirect with owner",
		"rooms": "5",
		"price": "5900 CHF",
		"location": "Pellegrino-Rossi 16, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87562_bl_photo_e2421.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87676",
		"title": "Furnished 3.5 Rooms two Balconies, Close to Tram Station Place Favre",
		"desc": "A 4.5 room Flat where you can use 3.5 Rooms (1 Bedroom, Kitchen, Living-room, separate shower and toilette,2 balconies)<br />\r\nThe Flat is in Chene Bougeries, fully equipped, possible to use the Internet.<br />\r\nIt would also be possible to take over the lease (Flat rent is 2400.-, which might get increased by the regie.",
		"rooms": "4",
		"price": "2100 CHF",
		"location": ", Chene Bougeries",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87676_bl_photo_4fbdd.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87460",
		"title": "House in Chambésy for Sale",
		"desc": "This 7-room single family home is situated in Chambésy and built in 2008. It is very private and enjoys beautiful natural surroundings by bordering the Chambésy forest.  It is also very close to the Chambésy sports center, which has a swimming pool and tennis courts etc. Residents of Chambésy may also have access to the private Chambésy beach.<br />\r\nThe house comes with 4 bedrooms (2 suites). The three bedrooms, including the master bedroom, are on the top floor with high ceilings. The master bedroom is bright and spacious, with a balcony overlooking the garden. With doors and large windows all around, the living area benefits from ample natural light throughout the day. It also has a built-in fireplace. The kitchen is spacious with ample bench space and cupboards. The basement comes with another large suite and other rooms. Due to the smart design, the basement also benefits from natural light.  <br />\r\nIn addition to its generous living space of more than 175 m2, the house also comes with a large atomic shelter, a sun-room of 20 m2, 2 underground parking with access to the basement, security alarms, and a cabin in the garden.",
		"rooms": "7",
		"price": "2170000 CHF",
		"location": ", Chambésy, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87460_bl_photo_ae2bd.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87672",
		"title": "4 piece apartment, partially furnished, Gd Saconnex, beautiful view of Jura",
		"desc": "Close to UN, WHO, Global Fund and other International Organisations. 6th floor. Partially furnished, bright - big living room with wide windows, balcony with view of mountains and parks. 2 bedrms, and fully equipped kitchen. <br />\r\nAvailable immediately until end of March for 2500 Sfr.",
		"rooms": "4",
		"price": "2500 CHF",
		"location": "Grand Saconnex, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87672_bl_photo_e1178.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87568",
		"title": "4.5 rooms in Servette - UN / gare Cornavin area, take over bail",
		"desc": "I am giving away this very nice apt which I stayed in for 4 years AND which I also found via glocals:<br />\r\n<br />\r\n- modern, very bright abt 76m2 at 8th floor<br />\r\n- American kitchen<br />\r\n- 2 bed rooms, master and kid's (or office)<br />\r\n- all rooms with bottom - top glass windows<br />\r\n- extra bath room, extra toilet - both dry and clean<br />\r\n- 2 built-in spacious cupboards<br />\r\n- electric shades in living and 2 bedrooms<br />\r\n- 2 lifts <br />\r\n- dry and spacious cave<br />\r\n- Denner at corner of the building, Migros / Coop in walking distance<br />\r\n- bus nr 8 (2 minutes to Cornavin), nr 5 (airport in 12 minutes)<br />\r\n- tram 14,18 and bus 3 in walking distance (Servette)<br />\r\n- public pool Varembé 1 block away",
		"rooms": "4",
		"price": "2500 CHF",
		"location": "Servette - Varembé, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87568_bl_photo_b437a.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87667",
		"title": "4.5 rooms, Champel, with 2 gardens.",
		"desc": "Old building, flat with high ceilings, fireplace, 2 gardens.<br />\r\n<br />\r\nOne big bedroom,<br />\r\nOne small bedroom,<br />\r\nOne living-room,<br />\r\nOne dining room<br />\r\nOne bath-room<br />\r\nOne separate toilet and one kitchen.",
		"rooms": "5",
		"price": "3500 CHF",
		"location": "Champel, Genève",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87667_bl_photo_7ae52.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "82617",
		"title": "Spacious furnished, fully equipped rooftop apartment for rent in Vallorbe (in the canton of Vaud)",
		"desc": "Spacious furnished, fully equipped rooftop apartment for rent in Vallorbe (in the canton of Vaud) <br />\r\nchf 1100 per month<br />\r\nLiving room, bedroom, kitchen, bathroom with shower and toilet, corridor, half room (for 2nd bedroom) storage space, with access to a large garden, heating with a wood stove, 5 minutes by foot from the Vallorbe train station (for connections to Yverdon, Lausanne and Geneva)<br />\r\nAvailable 15 March 2019<br />\r\nIf you are interested please telephone Mobile 078 614 83 67 or send an email to vallorbe@icloud.com<br />\r\nPhotos available on request<br />\r\nThank you",
		"rooms": "4",
		"price": "1100 CHF",
		"location": "Vallorbe, Vallorbe",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals0"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87254",
		"title": "&quot;La Motte&quot; - Character 2-/3-bed house, garden, parking, playhouse/studio, Ferney",
		"desc": "Must be seen! Rare chance to rent \"La Motte\" - a beautiful two-/three-bedroomed house with old stone, beams and  mature garden with fruit trees in central Ferney-Voltaire. Available furnished, unfurnished or semi-furnished. Direct buses to station, airport, UN, WHO, ILO, CERN etc. Stone’s throw from Ferney's famous Saturday market, cafés, restaurants and superb boulangerie. Close walking distance to shops, cinema, theatres.<br />\r\n    Spacious stone terrace with mosaic table and metal chairs, PLUS small separate two-storey 18th-century outhouse which can be used as playhouse/study/studio/ artist's atelier or storage. <br />\r\n   Covered- off-street parking, safe locked storage for bicycles and other items.<br />\r\n    Ground floor: comfortable kitchen-diner-living room with ancient beams and huge stone-framed arched window, said to have come from one of Voltaire's theatres. In kitchen area: 80-cm electric oven with gas burners, large fridge-freezer, dishwasher, built-in washer/drier. In living area: handsome wood-fired stove, rustic antique dining table (as an option). Hall with antique wardrobe and chest of drawers, plus plentiful under-stair storage. <br />\r\n   First floor: large main bedroom with two stone-framed windows overlooking garden; plentiful cupboard space. (This room was two bedrooms, and can easily be restored to two for any medium- or long-term tenant.) Second bedroom/study with built-in wardrobe. Bathroom, separate WC. <br />\r\n   Garden: 1,200 square metres of mature garden with fruit and nut trees, and a row of ancient gravestones (no bodies!). <br />\r\n     Property available furnished or semi-furnished for medium- or long-term rent. Extra guest room(s) for visitors may be rented for modest fees from proprietor David Lewis, ex-WHO and EBU, who lives in an adjacent part of the property. <br />\r\n   Perfect for couple or couple and child (swing, trapeze and rope on large frame in garden).  <br />\r\n   CHF 2,650 per calendar month (or euro equivalent), plus CHF 250 to cover all charges (electricity, gas, water, garbage, insurance …). <br />\r\n   Previous tenants include employees of CERN, WHO and UNICEF.<br />\r\n   Call David or email him on davidxlewis@gmail.com for more details or photos and/or to discuss and arrange viewing. Tel: +33 450 40 52 92 or mobile/WhatsApp +33 783 12 21 15.",
		"rooms": "4",
		"price": "2650 CHF",
		"location": "22 rue de Genève, Ferney Voltaire",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87254_bl_photo_29eb9.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87653",
		"title": "Paquis 4 P / 2 bedrooms flat available  from 1st April 201 or earlier",
		"desc": "Great flat of 4 pieces with balcony in Rue de la Navigation, 5th floor, very sunny, parquet, two bedrooms, bathroom and separate WC, fireplace, cellar, rent includes heating and charges, very close to the lake, coop & migros around the corner VISITS on Wednesday 27th FEB and Friday 1st MARCH from 18h30 to 20h, if needed visits on demand <br />\r\n<br />\r\nBelle appartement de 4 pièces avec balcon à rue de la Navigation, 5ème étage, très ensoleillé, parquet, deux chambres à coucher, salle de bains et WC séparés, cheminée, cave, le loyer inclut chauffage et charges, très proche du lac, coop & migros autour du coin VISITES les mercredi 27 février et vendredi 1er mars de 18h30 à 20h, si nécessaire visites sur demande",
		"rooms": "4",
		"price": "2200 CHF",
		"location": "Rue de la Navigation, Geneve",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87653_bl_photo_137f3.jpg"
	},
	{
		"origin": "glocals.com",
		"origin_id": "86981",
		"title": "Panoramic spacious 7 pieces (4 bedrooms) 167 sqm 7th fl in Champ Frechet, Meyrin",
		"desc": "A very spacious 167 SQ M, 7 pieces unfurnished beautiful corner apartment on the 7th floor in a upper class residential building is available immediately for rent at 10 Rue des Bugnons, Champ Frechets, Meyrin. <br />\r\n<br />\r\n It has 4 bedrooms, the master bedroom has its own private area with bathroom, wardrobes and changing area. For three other bedrooms, there is another full bathroom. The living and dining room is very spacious with big windows giving you a beautiful and panoramic view of the country side. The kitchen is very big and fully equipped with enough space for breakfast table. There are two balconies L type giving you plenty of sunshine. The apartment is divided by large corridors giving you a feeling of independence and privacy. It has a big entrance hall with another washroom. There are 6 big fitted wardrobes as well plus garage and store room. <br />\r\n<br />\r\n The apartment is a walking distance to indoor/outdoor swimming pool, ice skating rink, public stadium, schools, tram and buses and big shopping area. 5 minutes by car to shopping in France and airport.  A very safe place for children to play outside in front of the building. There are plenty of free parkings available. It is very quiet and sunny. There are plenty of walks to enjoy for health purpose. <br />\r\n<br />\r\n The rent is Sfr 4950 per month plus Sfr 250 charges negotiable. <br />\r\n<br />\r\n For visit, please contact the owner: <br />\r\n<br />\r\n Vinay Khosla <br />\r\n<br />\r\n Tel: 076-474 8036 (Mobile & Whatsapp)<br />\r\n<br />\r\n Email: vinay.khosla@hotmail.com",
		"rooms": "7",
		"price": "4950 CHF",
		"location": "Champ Frechets, Meyrin, Geneva",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals0"
	},
	{
		"origin": "glocals.com",
		"origin_id": "87042",
		"title": "PETIT-SACONNEX, 7 ROOMS APARTMENT OF 165 SQM",
		"desc": "In the town of Le Petit-Saconnex, beautiful 7-room apartment of 165 sqm, in the International Organisations sector<br />\r\n<br />\r\n- Entrance hall with lockers<br />\r\n- Equipped kitchen<br />\r\n- Large living room with balcony access<br />\r\n- 3 bedrooms<br />\r\n- 2 bathrooms / showers<br />\r\n- Separate toilet<br />\r\n- Versatile part with sliding door<br />\r\n- Visitor's WC<br />\r\n<br />\r\nCellar<br />\r\nBox for 1 car in the basement (included)<br />\r\n<br />\r\nClose to all conveniences",
		"rooms": "7",
		"price": "4990 CHF",
		"location": ", Petit-Saconnex",
		"url": "",
		"area": "",
		"pic": "https://cdn.glocals.com/sites/glocals/_media/board_flat1/87/87042_bl_photo_72036.jpg"
	}
]);